development:
  adapter: postgresql
  encoding: unicode
  database: locatemyautos_development
  pool: 5
  username: locatemyautos
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: locatemyautos_production
  pool: 5
  username: locatemyautos
  password: